export const CafeData = [
  {
    typename: "Cafe",
    id: "1",
    name: "Breka (Main)",
    street: "4554 Main St",
    city: "Vancouver",
    province: "BC",
    price: 2,
    noisiness: 2,
    busyness: 3,
  },
  {
    typename: "Cafe",
    id: "2",
    name: "Grounds for Coffee",
    street: "2088 Commercial Dr",
    city: "Vancouver",
    province: "BC",
    price: 1,
    noisiness: 1,
    busyness: 2,
  },
  {
    typename: "Cafe",
    id: "3",
    name: "Nemesis Coffee (GNW)",
    street: "555 Great Northern Way",
    city: "Vancouver",
    province: "BC",
    price: 3,
    noisiness: 1,
    busyness: 3,
  },
  {
    typename: "Cafe",
    id: "4",
    name: "49th Parallel Café & Lucky's Doughnuts (W 4th)",
    street: "2198 W 4th Ave",
    city: "Vancouver",
    province: "BC",
    price: 2,
    noisiness: 3,
    busyness: 2,
  },
  {
    typename: "Cafe",
    id: "5",
    name: "Bean Around the World (S Granville)",
    street: "2977 Granville St",
    city: "Vancouver",
    province: "BC",
    price: 1,
    noisiness: 2,
    busyness: 1,
  },
];
